postgis:
        image: postgis/postgis:12-3.0
        restart: on-failure
        hostname: postgis
        environment:
          POSTGRES_PASSWORD: "password"
          POSTGRES_USER: "user"
        ports:
        - 5432:5432
        volumes:
        - ./postgis-data:/var/lib/postgresql/data
        - ./postgis-import-folder:/data-import

